import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Add invite code column to schools table for parent registration
 *
 * Stores 8-character uppercase alphanumeric invite codes.
 * Auto-generated on school creation, can be regenerated by admins.
 */
export class AddInviteCodeToSchools1712000000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Add invite_code column as nullable
    await queryRunner.query(`
      ALTER TABLE "schools"
      ADD COLUMN "invite_code" varchar(8) UNIQUE
    `);

    // Backfill existing schools with generated codes
    await queryRunner.query(`
      UPDATE "schools"
      SET "invite_code" = upper(substring(md5(random()::text) from 1 for 8))
      WHERE "invite_code" IS NULL
    `);

    // Set invite_code as NOT NULL
    await queryRunner.query(`
      ALTER TABLE "schools"
      ALTER COLUMN "invite_code" SET NOT NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "schools" DROP COLUMN IF EXISTS "invite_code"
    `);
  }
}
